name: Docker

on:
  push:
    branches:
      - main

  # Run every day at midnight
  schedule:
    - cron:  '* 0 * * *'

env:
  IMAGE_NAME: steamcmd
  CR_PAT: ${{ secrets.CR_PAT }}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Bazel
        run: |
          apt install apt-transport-https curl gnupg
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
          mv bazel.gpg /etc/apt/trusted.gpg.d/
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          apt update && sudo apt install bazel

      - name: Log into registry
        run: echo "$CR_PAT" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        run: bazel run :push_steamcmd_image